config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  get 'home/create_channel'
  get 'home/host'
  get 'home/client'
  resources :rtcons
   root to: "home#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rtcon.rb
class Rtcon < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
    @other_users = User.where.not(id: current_user.id)
    @channel_status  = current_user.rtc_id ? true : false

  end

  def create_channel
    current_user.update_attributes(:rtc_id => SecureRandom.uuid)
    redirect_to home_index_path
  end


  def host 
    
  end

  def client
    @user = User.find(params[:uid])
  end
end

app/controllers/rtcons_controller.rb
class RtconsController < ApplicationController
  before_action :set_rtcon, only: [:show, :edit, :update, :destroy]

  # GET /rtcons
  # GET /rtcons.json
  def index
    @rtcons = Rtcon.all
  end

  # GET /rtcons/1
  # GET /rtcons/1.json
  def show
  end

  # GET /rtcons/new
  def new
    @rtcon = Rtcon.new
  end

  # GET /rtcons/1/edit
  def edit
  end

  # POST /rtcons
  # POST /rtcons.json
  def create
    @rtcon = Rtcon.new(rtcon_params)

    respond_to do |format|
      if @rtcon.save
        format.html { redirect_to @rtcon, notice: 'Rtcon was successfully created.' }
        format.json { render :show, status: :created, location: @rtcon }
      else
        format.html { render :new }
        format.json { render json: @rtcon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rtcons/1
  # PATCH/PUT /rtcons/1.json
  def update
    respond_to do |format|
      if @rtcon.update(rtcon_params)
        format.html { redirect_to @rtcon, notice: 'Rtcon was successfully updated.' }
        format.json { render :show, status: :ok, location: @rtcon }
      else
        format.html { render :edit }
        format.json { render json: @rtcon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rtcons/1
  # DELETE /rtcons/1.json
  def destroy
    @rtcon.destroy
    respond_to do |format|
      format.html { redirect_to rtcons_url, notice: 'Rtcon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rtcon
      @rtcon = Rtcon.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rtcon_params
      params.fetch(:rtcon, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rtcons_helper.rb
module RtconsHelper
end

app/views/home/client.html.erb
<%# ,:id => 'conn', :data => { :uid => u.id, :rid => u.rtc_id   %>
Status: <pre id='status'>Connecting..</pre><br>
<%= text_field_tag "msg","",:id => "msg"%>
<button type="button" id="send">Send</button>
<button type="button" id="call">Call</button>
<video controls muted id='myVid'></video><br>
<video id='yourVid'></video>
<video id='yourScreen'></video>
<br>
<pre id='message'></pre>
<script>
    var con1 = null;
    var peer = null;
    var conn = null;
    var lastPeerId = null;
    var joinfn;
    (function(){
        //var url1 = 'localhost';
        var url1 = 'ec2-3-22-202-169.us-east-2.compute.amazonaws.com';
        var stat = document.getElementById('status');
        var mg = document.getElementById('message');
        var send = document.getElementById('send');
        var myVid = document.getElementById('myVid');
        var yourScreen = document.getElementById('yourScreen');
        var myStream = null;
        var constraints = {
            audio: true,
            video: { width: 400, height: 400 }
        }
        navigator.mediaDevices.getUserMedia(constraints)
            .then((stream) => {
                myVid.srcObject = stream;
                myStream = stream;
                myVid.onloadedmetadata = function(e) {
                    myVid.play();
                };
            })
            .catch( err => { console.log(err)})
        function initialize() {

            peer = new Peer({
            host: url1,
            port: 9000,
            path: '/myapp',
            debug: 2,
//            config: {'iceServers': [
//                { url: 'stun:stun.l.google.com:19302' },
//                { url: 'stun:stun1.l.google.com:19302' },
 //           ]}
            });
            peer.on('open',function(id) {
                if (peer.id === null) {
                    console.log('Received null id from peer open');
                    peer.id = lastPeerId;
                } else {
                    lastPeerId = peer.id;
                }
                stat.innerHTML = "Connection ready :" + id;
		        joinfn();
            });

            peer.on('disconnected', function () {
                stat.innerHTML = "Connection lost. Please reconnect";

                // Workaround for peer.reconnect deleting previous id
                peer.id = lastPeerId;
                peer._lastServerId = lastPeerId;
                peer.reconnect();
            });
	

	    peer.on('error', function(err) {
		    stat.innerHTML = "err: " + err.type;
	    });

            peer.on('close', function() {
                conn = null;
                stat.innerHTML = "Connection destroyed. Please refresh";
                console.log('Connection destroyed');
            });

        }
        joinfn = function() {
            if (conn) {
                conn.close();
            }
            conn = peer.connect('<%= @user.rtc_id %>', {
                reliable: true
            });
            conn.on('open', function () { 
		  
                stat.innerHTML = "Connected to Host" ;//: <%= @user.email%>" ;
            });

            conn.on('data', function (data) {
                mg.innerHTML += ("<%=@user.email%> :" + data + "\n");
            });

            conn.on('close', function () {
                stat.innerHTML = "Connection closed";
            });

		conn.on('error', function(err) {
			stat.innerHTML = 'error';
			console.log(err);
	    });

        }

            initialize();

        send.addEventListener( 'click', function(){
            if (conn && conn.open){
                mg.innerHTML += "me: " + msg.value + "\n";
                conn.send(msg.value);   
                msg.value = ""; 
            } else {
                console.log("no connection");
            }
        });
        call.addEventListener( 'click', function(){
		call = peer.call('<%= @user.rtc_id %>',myStream);

		call.on('stream', function(stream) {
		    yourVid.srcObject = stream;
		    yourVid.play();
		});
        });
    })();
</script>

app/views/home/host.html.erb
rtcid: <%=current_user.rtc_id%><br>
Status: <pre id='status'></pre><br>
<%= text_field_tag "msg","",:id => "msg"%>
<button type="button" id="send">Send</button>
<video id='myVid'></video><br>
<video id='yourVid'></video><br>
<pre id='message'></pre>
<script>
    var peer = null;
    var conn = null;
    var call = null;
    (function () {
        var url1 = 'ec2-3-22-202-169.us-east-2.compute.amazonaws.com';
        //var url1 = 'localhost';
        var video = document.getElementById('myVid');
        var yourVid  = document.getElementById('yourVid');
        var myStream = null;
        var constraints = {
            audio: true,
            video: { width: 400, height: 400 }
        }
        constraints = {
            video: {
                mediaSource: "screen"
            }
        }
        navigator.mediaDevices.getUserMedia(constraints)
            .then((stream) => {
                myStream = stream;
                video.srcObject = stream;
                video.onloadedmetadata = function(e) {
                    video.play();
                };
            })
            .catch( err => { console.log(err)})
        var stat = document.getElementById('status');
        var send = document.getElementById('send');
        var mg = document.getElementById('message');
        var msg = document.getElementById('msg');
        var lastPeerId = null;
        function initialize() {
            peer = new Peer( '<%=current_user.rtc_id%>',{
            host: url1,
            port: 9000,
            path: '/myapp',
            debug: 2,
            config: {'iceServers': [
                        { url: 'stun:stun.l.google.com:19302' },
                        { url: 'stun:stun1.l.google.com:19302' },
                    ] 
                    }
            });
            peer.on('call', function(call) {
                // Answer the call, providing our mediaStream
                call.answer(myStream);
                call.on('stream',function(stream){
                    yourVid.srcObject = stream;
                    yourVid.play()
                })
            });



            peer.on('open', (conn) => {
                stat.innerHTML = "Host ready";
                if (peer.id === null) {
                        console.log('Received null id from peer open');
                        peer.id = lastPeerId;
                    } else {
                        lastPeerId = peer.id;
                }
            });
            peer.on('connection', (c) => {
                if (conn && conn.open) {
			console.log("iii");
                    c.on('open', function() {
                        c.send("Already connected to another client");
                        setTimeout(function() { c.close(); }, 500);
                    });
                    return;
                }
                conn = c;
                stat.innerHTML = "Client Connected";
                ready();
            });
            peer.on('close', function() {
                conn = null;
                stat.innerHTML = "Connection destroyed. Please refresh";
            });

            peer.on('disconnected', (conn) => {
                stat.innerHTML = "peer disconnected, Awaiting Connection";
                peer.id = lastPeerId;
                peer._lastServerId = lastPeerId;
                peer.reconnect();
            });


        }
        function ready() {
            conn.on('data', function (data) {
                mg.innerHTML += ("other guy :" + data + "\n");
            });
            conn.on('close', function () {
                status.innerHTML = "Connection reset<br>Awaiting connection...";
                conn = null;
            });
        }
        initialize();
        send.addEventListener( 'click', function(){
            if (conn ){
                mg.innerHTML += "me: " + msg.value + "\n";
                conn.send(msg.value);   
                msg.value = ""; 
            } else {
                console.log("no connection");
            }
        });
    })();
</script>

app/views/home/index.html.erb
<h1>Home#index</h1>
Welcome <%= current_user.email %><br>
<b>Channel Status: </b> <%= @channel_status%> <br>
<table>
  <tr><th>email</th><th>status</th><th>Connect</th></tr>
<% @other_users.each do |u| %>
	<tr>
  <td><%= u.email%></td>
  <td><%=u.host_status ? "Active" : "Inactive"%></td>
  <td>
  <% if u.host_status%>
  <%= link_to "connect","/home/client?uid=#{u.id}" %>
  <% end%>
  </td>
	</tr>
<% end %>
</table>
<%= link_to  "create channel", home_create_channel_path %> <br>
<%= link_to "join Host", "/home/host" , :id =>'ch'%>
<pre id='message'>
</pre>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myqpp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<%= link_to('Logout', destroy_user_session_path, method: :delete) %>   
    <%= yield %>
  </body>
</html>

app/views/rtcons/_form.html.erb
<%= form_with(model: rtcon, local: true) do |form| %>
  <% if rtcon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rtcon.errors.count, "error") %> prohibited this rtcon from being saved:</h2>

      <ul>
      <% rtcon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rtcons/edit.html.erb
<h1>Editing Rtcon</h1>

<%= render 'form', rtcon: @rtcon %>

<%= link_to 'Show', @rtcon %> |
<%= link_to 'Back', rtcons_path %>

app/views/rtcons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rtcons</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rtcons.each do |rtcon| %>
      <tr>
        <td><%= link_to 'Show', rtcon %></td>
        <td><%= link_to 'Edit', edit_rtcon_path(rtcon) %></td>
        <td><%= link_to 'Destroy', rtcon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rtcon', new_rtcon_path %>

app/views/rtcons/new.html.erb
<h1>New Rtcon</h1>

<%= render 'form', rtcon: @rtcon %>

<%= link_to 'Back', rtcons_path %>

app/views/rtcons/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_rtcon_path(@rtcon) %> |
<%= link_to 'Back', rtcons_path %>